Repository JinraeKim/FlightSims.jl, pull requests merged in 2021-06, with the labels that each got.

#27 Add backstepping position controller for multicopters
  Project.toml
  README.md
  src/APIs/simulation.jl
  src/FlightSims.jl
  src/algorithms/BacksteppingPositionController.jl
  src/algorithms/algorithms.jl
  src/algorithms/controllers.jl
  src/algorithms/reinforcement_learnings.jl
  test/algorithms/backstepping_position_controller.jl
  test/algorithms/behavioural_cloning.jl
  test/algorithms/continuous_time_vi_adp.jl
  test/environments/basics/two_dimensional_nonlinear_polynomial_env.jl
  test/environments/multicopters/goodarzi_quadcopter_env.jl
  test/lqr.jl
  test/sim_and_save.jl
Labels: enhancement

#32 Rename a file and change compat
  Project.toml
  src/FlightSims.jl
  src/algorithms/reinforcement_learnings.jl
Labels: bug

#35 Add command generator; Power Loop
  src/utils/CommandGenerator.jl
  src/utils/utils.jl
  test/utils/command_generator.jl
Labels: enhancement

#37 Update backstepping controller
  Project.toml
  README.md
  main/backstepping_tracking.jl
  src/APIs/data_processing.jl
  src/FlightSims.jl
  src/algorithms/algorithms.jl
  src/algorithms/controllers.jl
  src/environments/basics/ReferenceModelEnv.jl
  src/environments/basics/basics.jl
  src/environments/controllers/BacksteppingPositionControllerEnv.jl
  src/environments/controllers/controllers.jl
  src/environments/environments.jl
  src/environments/integrated_environments/integrated_environments.jl
  src/environments/multicopters/GoodarziQuadcopterEnv.jl
  src/utils/CommandGenerator.jl
  test/algorithms/backstepping_position_controller.jl
  test/environments/basics/reference_model_env.jl
  test/environments/controllers/backstepping_position_controller.jl
  test/environments/integrated_environments/integrated_environments.jl
  test/utils/command_generator.jl
Labels: enhancement

#39 Add mixers for quadcopters
  main/backstepping_tracking.jl
  src/FlightSims.jl
  src/environments/integrated_environments/integrated_environments.jl
  src/environments/multicopters/GoodarziQuadcopterEnv.jl
  src/environments/multicopters/IslamQuadcopterEnv.jl
  src/environments/multicopters/mixers.jl
  src/environments/multicopters/multicopters.jl
  src/environments/multicopters/quadcopters.jl
Labels: enhancement

#34 Reorganise README.md
  README.md
  figures/backstepping_tracking.png
  main/backstepping_tracking.jl
Labels: documentation

#40 Prepare v0.3.0
  Project.toml
  README.md
  figures/backstepping_tracking.png
  figures/lqr.png
  main/backstepping_tracking.jl
  main/flux_example.jl
  src/APIs/data_processing.jl
  src/APIs/simulation.jl
  src/FlightSims.jl
  src/algorithms/BehaviouralCloning.jl
  src/algorithms/algorithms.jl
  src/algorithms/reinforcement_learnings.jl
  src/environments/basics/LinearSystemEnv.jl
  src/environments/basics/ReferenceModelEnv.jl
  src/environments/basics/TwoDimensionalNonlinearPolynomialEnv.jl
  src/environments/basics/basics.jl
  src/environments/controllers/BacksteppingPositionControllerEnv.jl
  src/environments/controllers/controllers.jl
  src/environments/environments.jl
  src/environments/integrated_environments/integrated_environments.jl
  src/environments/multicopters/GoodarziQuadcopterEnv.jl
  src/environments/multicopters/IslamQuadcopterEnv.jl
  src/environments/multicopters/mixers.jl
  src/environments/multicopters/multicopters.jl
  src/environments/multicopters/quadcopters.jl
  src/utils/CommandGenerator.jl
  src/utils/partitionTrainTest.jl
  src/utils/utils.jl
  test/algorithms/behavioural_cloning.jl
  test/algorithms/continuous_time_vi_adp.jl
  test/environments/basics/reference_model_env.jl
  test/environments/basics/two_dimensional_nonlinear_polynomial_env.jl
  test/environments/controllers/backstepping_position_controller.jl
  test/environments/integrated_environments/integrated_environments.jl
  test/environments/multicopters/goodarzi_quadcopter_env.jl
  test/lqr.jl
  test/sim_and_save.jl
  test/utils/command_generator.jl
Labels: bug, documentation, enhancement

#41 Update compat; ForwardDiff
  Project.toml
Labels: bug, documentation

#42 Add fault models (embedded in quadcopters)
  Project.toml
  README.md
  src/FlightSims.jl
  src/environments/environments.jl
  src/environments/multicopters/GoodarziQuadcopterEnv.jl
  src/environments/multicopters/IslamQuadcopterEnv.jl
  src/environments/multicopters/multicopters.jl
  src/environments/multicopters/quadcopters.jl
  test/environments/multicopters/goodarzi_quadcopter_env.jl
  test/environments/multicopters/islam_quadcopter_env.jl
Labels: documentation, enhancement

#46 Recover disappeared fault models file
  src/environments/faults.jl
  src/environments/multicopters/quadcopters.jl
Labels: bug

#47 Hotfix2 for disappeared fault models file
  src/environments/faults.jl
Labels: bug

#48 Add hexacopter and refine integrated_environments
  src/FlightSims.jl
  src/environments/integrated_environments/integrated_environments.jl
  src/environments/multicopters/GoodarziQuadcopterEnv.jl
  src/environments/multicopters/IslamQuadcopterEnv.jl
  src/environments/multicopters/LeeHexacopterEnv.jl
  src/environments/multicopters/hexacopters.jl
  src/environments/multicopters/mixers.jl
  src/environments/multicopters/multicopters.jl
  src/environments/multicopters/quadcopters.jl
  test/environments/integrated_environments/integrated_environments.jl
  test/environments/multicopters/lee_hexacopter.jl
Labels: enhancement

#53 Fix a bug of LinearSystemEnv
  src/environments/basics/LinearSystemEnv.jl
Labels: bug

#54 Add saving API
  src/APIs/simulation.jl
  test/APIs/simulation.jl
Labels: enhancement

#56 Change APIs' name
  README.md
  figures/lqr.png
  main/backstepping_tracking.jl
  src/APIs/data_processing.jl
  src/APIs/define_env.jl
  src/APIs/simulation.jl
  src/FlightSims.jl
  src/environments/basics/LinearSystemEnv.jl
  src/environments/basics/ReferenceModelEnv.jl
  src/environments/basics/TwoDimensionalNonlinearPolynomialEnv.jl
  src/environments/controllers/BacksteppingPositionControllerEnv.jl
  src/environments/integrated_environments/integrated_environments.jl
  src/environments/multicopters/multicopters.jl
  test/APIs/simulation.jl
  test/algorithms/behavioural_cloning.jl
  test/algorithms/continuous_time_vi_adp.jl
  test/environments/basics/reference_model_env.jl
  test/environments/basics/two_dimensional_nonlinear_polynomial_env.jl
  test/environments/controllers/backstepping_position_controller.jl
  test/environments/integrated_environments/integrated_environments.jl
  test/environments/multicopters/goodarzi_quadcopter_env.jl
  test/environments/multicopters/islam_quadcopter_env.jl
  test/environments/multicopters/lee_hexacopter.jl
  test/load_and_plot.jl
  test/lqr.jl
  test/sim_and_save.jl
Labels: documentation

#57 Add `Params` and new feature `save_inputs`; add `LQR` (infinite-horizon continuous-time linear quadratic regulator)
  README.md
  figures/lqr.png
  figures/u_lqr.png
  figures/x_lqr.png
  main/backstepping_tracking.jl
  src/APIs/data_processing.jl
  src/APIs/define_env.jl
  src/APIs/simulation.jl
  src/FlightSims.jl
  src/environments/basics/LinearSystemEnv.jl
  src/environments/basics/TwoDimensionalNonlinearPolynomialEnv.jl
  src/environments/controllers/LQR.jl
  src/environments/controllers/controllers.jl
  test/APIs/simulation.jl
  test/algorithms/continuous_time_vi_adp.jl
  test/environments/basics/reference_model_env.jl
  test/environments/basics/two_dimensional_nonlinear_polynomial_env.jl
  test/environments/controllers/backstepping_position_controller.jl
  test/environments/integrated_environments/integrated_environments.jl
  test/load_and_plot.jl
  test/lqr.jl
Labels: bug, documentation, enhancement

#63 Prepare release v0.4.0
  Project.toml
  README.md
Labels: documentation

#65 Fix a bug of `test/algorithms/continuous_time_vi_adp.jl`
  src/algorithms/ADP.jl
  test/algorithms/continuous_time_vi_adp.jl
Labels: bug

#67 Prepare v0.4.1 (update README.md, fix bugs)
  Project.toml
  README.md
  figures/lqr.png
  figures/traj_multicopter_backstepping.png
  main/backstepping_tracking.jl
  src/environments/integrated_environments/integrated_environments.jl
Labels: bug, documentation

#68 hotfix; make a test file runnable
  src/environments/integrated_environments/integrated_environments.jl
  test/environments/integrated_environments/integrated_environments.jl
Labels: bug

#69 Rename mixer as control allocator
  main/backstepping_tracking.jl
  src/FlightSims.jl
  src/environments/allocators/AdaptiveControlAllocationEnv.jl
  src/environments/allocators/PseudoInverseControlAllocator.jl
  src/environments/allocators/allocators.jl
  src/environments/environments.jl
  src/environments/integrated_environments/integrated_environments.jl
  src/environments/multicopters/mixers.jl
  src/environments/multicopters/multicopters.jl
  test/environments/integrated_environments/integrated_environments.jl
Labels: documentation

#43 Add an irl example for linear system
  README.md
  src/FlightSims.jl
  src/algorithms/IRL.jl
  src/algorithms/reinforcement_learnings.jl
  src/environments/basics/IntegratorEnv.jl
  src/environments/basics/basics.jl
  src/environments/integrated_environments/integrated_environments.jl
  src/utils/costs.jl
  src/utils/utils.jl
  test/algorithms/continuous_time_linear_irl.jl
  test/environments/basics/integrator_env.jl
Labels: enhancement

#71 Rename command_generator as Command; update test files; Add default Process, etc.
  main/backstepping_tracking.jl
  src/APIs/data_processing.jl
  src/FlightSims.jl
  src/utils/CommandGenerator.jl
  test/utils/command_generator.jl
Labels: documentation, enhancement

#72 Add FDI
  main/backstepping_tracking.jl
  src/environments/FDI.jl
  src/environments/basics/ReferenceModelEnv.jl
  src/environments/controllers/BacksteppingPositionControllerEnv.jl
  src/environments/environments.jl
  test/environments/multicopters/fdi.jl
Labels: enhancement

#74 Prepare v0.5.0; Separate FTC (fault tolerant control)
  Project.toml
  README.md
  figures/traj_multicopter_backstepping.png
  main/backstepping_tracking.jl
  src/FlightSims.jl
  src/environments/FDI.jl
  src/environments/allocators/AdaptiveControlAllocationEnv.jl
  src/environments/allocators/PseudoInverseControlAllocator.jl
  src/environments/allocators/allocators.jl
  src/environments/controllers/BacksteppingPositionControllerEnv.jl
  src/environments/controllers/controllers.jl
  src/environments/environments.jl
  src/environments/faults.jl
  src/environments/integrated_environments/integrated_environments.jl
  src/environments/integrated_environments/linear_and_integrator.jl
  src/environments/multicopters/GoodarziQuadcopterEnv.jl
  src/environments/multicopters/LeeHexacopterEnv.jl
  src/environments/multicopters/hexacopters.jl
  src/environments/multicopters/multicopters.jl
  test/environments/controllers/backstepping_position_controller.jl
  test/environments/multicopters/fdi.jl
  test/environments/multicopters/islam_quadcopter_env.jl
Labels: documentation, enhancement

#75 Fix the mentioned issues
  src/algorithms/IRL.jl
  test/algorithms/continuous_time_linear_irl.jl
Labels: bug

#76 Update for ftc
  README.md
  src/APIs/simulation.jl
  src/environments/multicopters/GoodarziQuadcopterEnv.jl
  src/environments/multicopters/IslamQuadcopterEnv.jl
  src/environments/multicopters/LeeHexacopterEnv.jl
  test/lqr.jl
Labels: documentation, enhancement

#77 Add logger
  Project.toml
  README.md
  src/APIs/APIs.jl
  src/APIs/macros.jl
  src/APIs/simulation.jl
  src/FlightSims.jl
  src/environments/basics/LinearSystemEnv.jl
  src/environments/controllers/LQR.jl
  src/environments/multicopters/multicopters.jl
  test/APIs/macros.jl
  test/lqr.jl
  test/nested_envs.jl
Labels: documentation, enhancement

#78 Rename log_only as onlylog
  Project.toml
  README.md
  src/APIs/macros.jl
  src/FlightSims.jl
  test/APIs/macros.jl
Labels: documentation

#79 Update lqr example
  README.md
  figures/u_lqr.png
  figures/x_lqr.png
  test/lqr.jl
Labels: documentation

#80 Refine logger
  README.md
  src/APIs/APIs.jl
  src/APIs/macros.jl
  src/APIs/simulation.jl
  src/FlightSims.jl
  src/environments/basics/LinearSystemEnv.jl
  src/environments/environments.jl
  test/APIs/macros.jl
  test/lqr.jl
  test/nested_envs.jl
Labels: bug, documentation, enhancement

#81 Hotfix v0.6.2
  README.md
  src/APIs/types.jl
Labels: bug, documentation

#82 Separate logging tools
  Project.toml
  README.md
  src/APIs/APIs.jl
  src/APIs/macros.jl
  src/FlightSims.jl
Labels: Release, documentation, enhancement

#83 Update dependencies
  Project.toml
  src/FlightSims.jl
Labels: bug

#84 Prepare v0.7
  Project.toml
  README.md
  src/APIs/data_processing.jl
  src/APIs/simulation.jl
  src/FlightSims.jl
  src/environments/basics/ReferenceModelEnv.jl
  src/environments/multicopters/multicopters.jl
  test/environments/basics/reference_model_env.jl
  test/environments/multicopters/lee_hexacopter.jl
  test/lqr.jl
Labels: Release, bug, documentation, enhancement

#86 Update lqr example
  README.md
Labels: documentation

#87 Update SimulationLogger compat
  Project.toml
Labels: enhancement

#88 Update sim's output; df structure
  Project.toml
  README.md
  src/APIs/simulation.jl
  test/lqr.jl
Labels: documentation, enhancement

#89 Deprecate `save` and `load` for a while
  Project.toml
  README.md
  src/APIs/data_processing.jl
Labels: documentation, enhancement

#92 Add PID
  src/FlightSims.jl
  src/environments/basics/LinearSystemEnv.jl
  src/environments/controllers/LQR.jl
  src/environments/controllers/PID.jl
  src/environments/controllers/controllers.jl
  test/environments/basics/pid.jl
Labels: enhancement

#93 Update README.md
  README.md
Labels: documentation

#94 Fix a bug of logging; was not able to deal with empty dict
  Project.toml
  README.md
  src/APIs/simulation.jl
  src/FlightSims.jl
  src/environments/multicopters/multicopters.jl
  test/environments/controllers/pid.jl
Labels: bug

#95 Update Project.toml
  Project.toml
Labels: bug, documentation, enhancement

#96 Fix project toml for auto-merging
  Project.toml
Labels: bug

#97 Add MultipleEnvs
  README.md
  src/FlightSims.jl
  src/environments/basics/MultipleEnvs.jl
  src/environments/basics/basics.jl
  src/environments/controllers/PID.jl
  test/environments/basics/multipleenvs.jl
Labels: documentation, enhancement

#98 Add pseudo inverse allocator
  README.md
  src/FlightSims.jl
  src/environments/allocators/PseudoInverseAllocator.jl
  src/environments/allocators/allocators.jl
  src/environments/environments.jl
  test/environments/allocators/pseudo_inverse_allocator.jl
Labels: documentation, enhancement

#99 Restrict PID args
  README.md
  src/environments/controllers/PID.jl
  test/lqr.jl
Labels: bug, documentation

#100 Change how to deal with params in MultipleEnvs
  src/environments/basics/MultipleEnvs.jl
Labels: bug

#101 Organise exports
  README.md
  src/FlightSims.jl
  src/environments/allocators/PseudoInverseAllocator.jl
  src/environments/basics/LinearSystemEnv.jl
  src/environments/controllers/LQR.jl
  src/environments/controllers/PID.jl
  src/utils/rotations.jl
  test/lqr.jl
Labels: documentation, enhancement

#102 Bug fix for anti-windup of PID
  src/environments/controllers/PID.jl
Labels: enhancement
