Repository JinraeKim/FlightSims.jl, pull requests merged in 2021-09, with the labels that each got.

#119 Import backstepping controller env
  Project.toml
  src/FlightSims.jl
  src/environments/controllers/BacksteppingPositionControllerEnv.jl
  src/environments/controllers/controllers.jl
Labels: enhancement

#120 Add docs for backstepping
  Project.toml
  README.md
  src/environments/controllers/BacksteppingPositionControllerEnv.jl
  src/environments/integrated_environments/backstepping_position_controller_static_allocator_multicopter_env.jl
  src/environments/integrated_environments/integrated_environments.jl
  src/environments/multicopters/multicopters.jl
  test/environments/integrated_environments/backstepping_position_controller_static_allocator_multicopter_env.jl
  test/environments/integrated_environments/integrated_environments.jl
Labels: bug, enhancement

#121 Add a toy example
  README.md
  figures/toy_example.png
  test/toy_example.jl
Labels: documentation

#124 Fix a potential bug
  src/environments/integrated_environments/backstepping_position_controller_static_allocator_multicopter_env.jl
Labels: bug

#123 Test application -- Guidance -- 3D PPNG
  src/FlightSims.jl
  src/environments/controllers/PPNG.jl
  src/environments/controllers/controllers.jl
  src/environments/environments.jl
  src/environments/missiles/PointMass3DMissile.jl
  src/environments/missiles/PursuerEvador3DMissile.jl
  src/environments/missiles/missiles.jl
  test/environments/missiles/pursuer_evador_3d_missile.jl
  test/pluto_guidance.jl
Labels: enhancement

#129 Detach as fsimbase
  Project.toml
  README.md
  figures/toy_example.png
  src/APIs/APIs.jl
  src/APIs/data_processing.jl
  src/APIs/define_env.jl
  src/APIs/simulation.jl
  src/APIs/types.jl
  src/FlightSims.jl
  src/algorithms/ADP.jl
  src/algorithms/BehaviouralCloning.jl
  src/algorithms/IRL.jl
  src/algorithms/algorithms.jl
  src/algorithms/reinforcement_learnings.jl
  src/utils/approximators/LinearApproximator.jl
  src/utils/approximators/PolynomialBasis.jl
  src/utils/approximators/approximators.jl
  src/utils/utils.jl
  test/algorithms/behavioural_cloning.jl
  test/algorithms/continuous_time_linear_irl.jl
  test/algorithms/continuous_time_vi_adp.jl
  test/load_and_plot.jl
  test/lqr.jl
  test/sim_and_save.jl
  test/toy_example.jl
  test/utils/approximators/approximators.jl
  test/utils/approximators/linear_approximator.jl
  test/utils/approximators/polynomial_basis.jl
Labels: documentation, enhancement, Release

#131 Rename _sim to sim from fsimbase
  NEWS.md
  Project.toml
  README.md
  figures/hexacopter_description.png
  figures/topview.png
  figures/u_lqr.png
  figures/x_lqr.png
  main/flux_example.jl
  src/APIs/simulation.jl
  src/FlightSims.jl
  src/environments/multicopters/render.jl
  src/render.jl
  test/render.jl
Labels: bug, documentation

#137 Detach as FSimZoo
  NEWS.md
  Project.toml
  README.md
  src/FlightSims.jl
  src/environments/allocators/PseudoInverseAllocator.jl
  src/environments/allocators/allocators.jl
  src/environments/basics/IntegratorEnv.jl
  src/environments/basics/LinearSystemEnv.jl
  src/environments/basics/MultipleEnvs.jl
  src/environments/basics/ReferenceModelEnv.jl
  src/environments/basics/TwoDimensionalNonlinearPolynomialEnv.jl
  src/environments/basics/basics.jl
  src/environments/controllers/BacksteppingPositionControllerEnv.jl
  src/environments/controllers/LQR.jl
  src/environments/controllers/PID.jl
  src/environments/controllers/PPNG.jl
  src/environments/controllers/controllers.jl
  src/environments/environments.jl
  src/environments/integrated_environments/backstepping_position_controller_static_allocator_multicopter_env.jl
  src/environments/integrated_environments/integrated_environments.jl
  src/environments/integrated_environments/linear_and_integrator.jl
  src/environments/missiles/PointMass3DMissile.jl
  src/environments/missiles/PursuerEvador3DMissile.jl
  src/environments/missiles/missiles.jl
  src/environments/multicopters/GoodarziQuadcopterEnv.jl
  src/environments/multicopters/IslamQuadcopterEnv.jl
  src/environments/multicopters/LeeHexacopterEnv.jl
  src/environments/multicopters/hexacopters.jl
  src/environments/multicopters/multicopters.jl
  src/environments/multicopters/quadcopters.jl
  src/utils/CommandGenerator.jl
  src/utils/utils.jl
  test/APIs/macros.jl
  test/APIs/simulation.jl
  test/environments/allocators/pseudo_inverse_allocator.jl
  test/environments/basics/basics.jl
  test/environments/basics/integrator_env.jl
  test/environments/basics/multipleenvs.jl
  test/environments/basics/reference_model_env.jl
  test/environments/basics/two_dimensional_nonlinear_polynomial_env.jl
  test/environments/controllers/pid.jl
  test/environments/environments.jl
  test/environments/integrated_environments/backstepping_position_controller_static_allocator_multicopter_env.jl
  test/environments/integrated_environments/integrated_environments.jl
  test/environments/missiles/pursuer_evador_3d_missile.jl
  test/environments/multicopters/islam_quadcopter_env.jl
  test/environments/multicopters/lee_hexacopter.jl
  test/environments/multicopters/multicopters.jl
  test/lqr.jl
  test/nested_envs.jl
  test/pluto_guidance.jl
Labels: documentation

#139 Rename envs and move utils into FSimZoo
  README.md
  figures/toy_example.png
  src/FlightSims.jl
  src/utils/costs.jl
  src/utils/ned2enu.jl
  src/utils/partitionTrainTest.jl
  src/utils/utils.jl
  test/environments/integrated_environments/backstepping_position_controller_static_allocator_multicopter_env.jl
  test/lqr.jl
  test/utils/command_generator.jl
  test/utils/utils.jl
Labels: documentation, enhancement
